# Site Settings
title: Testausta 
email: taniarascia@gmail.com
description: >
  Enterin Tietoiskupankin testausta
baseurl: "/testEnter"
url: "http://tigerre1.github.io"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
