# Site Settings
title: Testausta 
email: rene.tigerstedt@gmail.com
description: >
  Enterin Tietoiskupankin testausta
baseurl: "/enterTest/"
url: "http://tigerre1.github.io"

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

